apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: robusta-torch-1

resources:
- ../../base

images:
  - name: ghcr.io/jrmanes/torch
    newTag: ac6e6ee

configMapGenerator:
- name: config
  files:
  - ./config/config.yaml
