mutualPeers:
  - peers:
    - nodeName: "bridge-1"
    - nodeName: "full-1"
  - peers:
    - nodeName: "bridge-2"
    - nodeName: "full-2"
  - peers:
    - nodeName: "bridge-2"
    - nodeName: "full-3"
