---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mp-orch
  name: mp-orch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mp-orch
  template:
    metadata:
      labels:
        app: mp-orch
    spec:
      serviceAccountName: mp-orch # Use the pod-reader service account
      containers:
      - image: localhost:5000/mp-orch:latest
        name: mp-orch
        command:
          - /bin/sh
          - -c
        args:
          - ./mp-orch --config-file /config/config.yaml
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "250Mi"
            cpu: "250m"
      volumes:
      # You set volumes at the Pod level, then mount them into containers inside that Pod
      - name: config
        configMap:
          # Provide the name of the ConfigMap you want to mount.
          name: config
          # An array of keys from the ConfigMap to create as files
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mp-orch
  name: mp-orch
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mp-orch
  type: ClusterIP
---
apiVersion: v1
data:
  config.yaml: |
    mutualPeers:
      - peers:
        - label: "app: bridge-1"
        - label: "app: full-1"
      - peers:
        - label: "app: bridge-2"
        - label: "app: full-2"
      - peers:
        - label: "app: bridge-2"
        - label: "app: full-3"
kind: ConfigMap
metadata:
  name: config
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mp-orch
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mp-orch-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mp-orch-binding
subjects:
- kind: ServiceAccount
  name: mp-orch
  namespace: default
roleRef:
  kind: ClusterRole
  name: mp-orch-role
  apiGroup: rbac.authorization.k8s.io
