apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../../base

images:
  - name: ghcr.io/celestiaorg/torch
    newTag: v0.0.1

configMapGenerator:
- name: config
  files:
  - ./config/config.yaml