apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../base

images:
  - name: github.com/jrmanes/torch
    newTag: 8ca7289

configMapGenerator:
- name: config
  files:
  - ./config/config.yaml
