mutualPeers:
  - peers:
    - nodeName: "da-bridge-1-0"
      containerName: "da"
    - nodeName: "da-full-1-0"
      containerName: "da"
    - nodeName: "da-full-2-0"
      containerName: "da"
    - nodeName: "da-full-3-0"
      containerName: "da"
    - nodeName: "da-full-4-0"
      containerName: "da"
    trustedPeersPath: "/tmp/celestia-config" # same as: SETUP_PATH
  - peers:
    - nodeName: "da-bridge-2-0"
      containerName: "da"
    - nodeName: "da-full-5-0"
      containerName: "da"
    - nodeName: "da-full-6-0"
      containerName: "da"
    - nodeName: "da-full-7-0"
      containerName: "da"
    - nodeName: "da-full-8-0"
      containerName: "da"
  - peers:
    - nodeName: "da-bridge-3-0"
      containerName: "da"
    - nodeName: "da-full-9-0"
      containerName: "da"
    - nodeName: "da-full-10-0"
      containerName: "da"
    - nodeName: "da-full-11-0"
      containerName: "da"
    - nodeName: "da-full-12-0"
      containerName: "da"
  - peers:
    - nodeName: "da-bridge-4-0"
      containerName: "da"
    - nodeName: "da-full-13-0"
      containerName: "da"
    - nodeName: "da-full-14-0"
      containerName: "da"
    - nodeName: "da-full-15-0"
      containerName: "da"
    - nodeName: "da-full-16-0"
      containerName: "da"
  - peers:
    - nodeName: "da-bridge-5-0"
      containerName: "da"
    - nodeName: "da-full-17-0"
      containerName: "da"
    - nodeName: "da-full-18-0"
      containerName: "da"
    - nodeName: "da-full-19-0"
      containerName: "da"
    - nodeName: "da-full-20-0"
      containerName: "da"